// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as ProductCategoryItemRoute from "@/app/product/[category]/[item]/page.info";
import * as StoreRoute from "@/app/store/page.info";
import * as StudentSlugRoute from "@/app/student/[...slug]/page.info";
import * as UserSlugRoute from "@/app/user/[slug]/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const ProductCategoryItem = makeRoute(
  "/product/[category]/[item]",
  {
    ...defaultInfo,
    ...ProductCategoryItemRoute.Route
  }
);
export const Store = makeRoute(
  "/store",
  {
    ...defaultInfo,
    ...StoreRoute.Route
  }
);
export const StudentSlug = makeRoute(
  "/student/[...slug]",
  {
    ...defaultInfo,
    ...StudentSlugRoute.Route
  }
);
export const UserSlug = makeRoute(
  "/user/[slug]",
  {
    ...defaultInfo,
    ...UserSlugRoute.Route
  }
);

